#!/bin/bash

chown root:wheel /etc/AdBlocker
chmod 755 /etc/AdBlocker
chown root:wheel /etc/AdBlocker/modified
chmod 644 /etc/AdBlocker/modified
chown root:wheel /etc/AdBlocker/default
chmod 644 /etc/AdBlocker/default
echo "Writing modification."
cp -a /etc/AdBlocker/modified /etc/hosts
echo "Complete!"
echo "Finishing some background process."
rm -rf .git
echo "Finished!"
echo "Enjoy! No options to configure"
echo "Please let me know if you find any ads you want me to patch!"
exit 0
